language: python
python:
  - 3.6

before_install: 
  - pip3 install numpy

install: 
  - pip3 install -r requirements.txt
  - pip3 install nose

script:
  - nosetests tests/data.py
  - nosetests tests/engine.py
  - nosetests tests/exchange.py
  - nosetests tests/helpers.py